### ISSUE TITLE
Type Error  when using bdd.dump('awesome.pdf')

### ISSUE THREAD

**Issue by digitalw** [johnyf/dd#24]
When executing the example https://github.com/johnyf/dd/blob/master/doc.md#plotting i get following error: 

    File "/home/bwright/.local/lib/python3.5/site-packages/dd/autoref.py", line 165, in dump
    roots = [u.node for u in roots]       
    TypeError: 'NoneType' object is not iterable       

 I am using version dd-0.4.3 as instllaed by `pip3 install dd`

Thanks for the Help
cheers 
Benedict

**Comment by slivingston** [comment]
I suspect that in commit 47fa10b435d8a02348a2d1a4d86faae7cbdfb127, a block conditional on whether `roots` is `None` should have been added, like in the method [`collect_garbage`](https://github.com/johnyf/dd/blob/137b23b428f5ad834830c3167c6869f89e45bb70/dd/autoref.py#L159).

In this case, I propose the following patch
```diff
diff --git a/dd/autoref.py b/dd/autoref.py
index 8b8e08e..22a8832 100644
--- a/dd/autoref.py
+++ b/dd/autoref.py
@@ -162,7 +162,8 @@ class BDD(object):
 
     def dump(self, filename, roots=None,
              filetype=None, **kw):
-        roots = [u.node for u in roots]
+        if roots is not None:
+            roots = [u.node for u in roots]
         self._bdd.dump(filename, roots=roots,
                        filetype=filetype)
```

**Comment by slivingston** [comment]
While my patch is considered, @digitalw in the example you can try to change the call to `dump` by passing a list with the expression node:

    bdd.dump('awesome.pdf', roots=[u])

**Comment by johnyf** [comment]
@digitalw thank you for reporting this. @slivingston thanks for the patch, applied as 121b96478bf29e9627732d849fd86c0998594634.

The example in the documentation was introduced in 078b1d35323ff684648c60abac548621b9fb972d. At that time `autoref.BDD.dump` [did not have a `roots` argument](https://github.com/johnyf/dd/blob/078b1d35323ff684648c60abac548621b9fb972d/dd/autoref.py#L132). The argument `roots` was introduced later, but `autoref` not updated.

One item for some time now in my list is to test `autoref`. It is only a thin wrapper around `dd.bdd`, so testing it can introduce duplication. One way to avoid duplication is to collect common tests for the (nearly identical) interface implemented by `autoref`, `cudd`, and `sylvan`. These tests can then be reused. It seems that it is best to specify the interface with an abstract base class implemented by each of these modules. These steps is one reason why I haven't yet tested `autoref` on its own.

For posterity, `master` at this time is at: https://github.com/johnyf/dd/blob/137b23b428f5ad834830c3167c6869f89e45bb70/doc.md#plotting

**Comment by digitalw** [comment]
Hi,
Thanks for the quick reply.
 @slivingston thats what I with then in the end.
