### ISSUE TITLE
test with Python 3 on Travis

### ISSUE THREAD

**Issue by johnyf** [johnyf/dd#5]
To ensure that the code base is compatible with both Python 2 and 3.

**Comment by maweki** [comment]
Travis has changed some of its process making the current config incompatible, not triggering builds. I will fix it and present a pull-request soon.

**Comment by johnyf** [comment]
I tend to disable travis during time periods away from releases, in order to reduce their load.
In the future, I will probably follow a convention to [whitelist on travis](http://docs.travis-ci.com/user/customizing-the-build/#Using-regular-expressions):

- branch `master`
- pull requests, and
- branches matching `travis_*` or so.

This appears to be a clean convention between travis and push activity. Whenever one wants to trigger a build, they can explicitly do so by pushing a duplicate of their current branch, prefixed with `travis_`. This will avoid unnecessary load on travis, w/o commit noise, neither requiring manually managing enabled branches on travis.

**Comment by johnyf** [comment]
Addressed by #6, a911167581ba0b5d231a700e16859ca2f25a970c, e4231669492bfb2648ccf125ff8b7f65534f8858.
